spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    
token:
  expiration_time: 86400000
  secret: '{cipher}AQBp2LEuQAYqyJ1+YGYqBByQ8FASssXA6c6O6QTWQ/Xe2DnNhvnvnqoj3fLGTD6K7qr0WfsDSdOv16fT9tHNDgF8KCVEXIBS1p34f7s2TcaAwE9vYze+FBJxCCJnBhVTEy4ldkxskghldvG9LAJqZEFQeKdlYkTFfdnn3MTRGGbuz08fg6vaDIHtJ0ExrFh1j/NdUdwS+/TSUmmw8QULV7GEhEWRxn0wHXaYXzk9YZt/BPqNTFGhlZhzkJYkea5RfP3z1rH5fsoIgEwLEMm9z6joVVfvutMEUkRcAXsM+MxZ2Ppru4u2i5viEsJ+63TfX56mBZ8bdCI0wRYikAFgLvAEy6W5+x2KO86pHJbFK8qdrYgHFo7fu9BM2TYWooDC2gKpvD64/EeF435++4zzeA4v'

gateway:
  ip: 172.30.0.4